import { useState } from "react";
import { useForm } from "react-hook-form";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Fuel, Plus, ReceiptText, X } from "lucide-react";
import toast from "react-hot-toast";
import { createExpense, createFuelLog, getExpenses, getFuelLogs } from "@/api/finance";
import { getVehicles } from "@/api/vehicles";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useOperationsRealtime } from "@/hooks/useOperationsRealtime";
import type { ExpenseType } from "@/types";

type FuelForm = { vehicleId: string; liters: number; cost: number; date: string }; type ExpenseForm = { vehicleId: string; type: ExpenseType; amount: number; date: string; description: string };
const today = () => new Date().toISOString().slice(0, 10);
export function FuelExpensesPage() {
  useOperationsRealtime(); const queryClient = useQueryClient(); const [mode, setMode] = useState<"fuel" | "expense" | null>(null); const fuelForm = useForm<FuelForm>({ defaultValues: { vehicleId: "", liters: 0, cost: 0, date: today() } }); const expenseForm = useForm<ExpenseForm>({ defaultValues: { vehicleId: "", type: "TOLL", amount: 0, date: today(), description: "" } });
  const { data: vehicles = [] } = useQuery({ queryKey: ["vehicles"], queryFn: () => getVehicles() }); const { data: fuelLogs = [], isLoading: fuelLoading } = useQuery({ queryKey: ["fuel-logs"], queryFn: getFuelLogs }); const { data: expenses = [], isLoading: expenseLoading } = useQuery({ queryKey: ["expenses"], queryFn: getExpenses }); const refresh = () => { ["fuel-logs", "expenses", "dashboard-kpis"].forEach((key) => queryClient.invalidateQueries({ queryKey: [key] })); };
  const addFuel = useMutation({ mutationFn: createFuelLog, onSuccess: () => { toast.success("Fuel log added"); setMode(null); fuelForm.reset({ vehicleId: "", liters: 0, cost: 0, date: today() }); refresh(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Unable to save fuel log") }); const addExpense = useMutation({ mutationFn: createExpense, onSuccess: () => { toast.success("Expense added"); setMode(null); expenseForm.reset({ vehicleId: "", type: "TOLL", amount: 0, date: today(), description: "" }); refresh(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Unable to save expense") });
  const fuelCost = fuelLogs.reduce((sum, log) => sum + log.cost, 0); const expenseCost = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-primary">Financial operations</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Fuel & expenses</h2><p className="mt-1 text-muted-foreground">Capture costs at vehicle level for accurate operational reporting.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setMode("expense")}><ReceiptText className="h-4 w-4" /> Add expense</Button><Button onClick={() => setMode("fuel")}><Plus className="h-4 w-4" /> Add fuel log</Button></div></div>
    {mode === "fuel" && <FormCard title="Add fuel log" onClose={() => setMode(null)}><form className="grid gap-4 md:grid-cols-4" onSubmit={fuelForm.handleSubmit((data) => addFuel.mutate({ ...data, liters: Number(data.liters), cost: Number(data.cost) }))}><VehicleField register={fuelForm.register} error={fuelForm.formState.errors.vehicleId?.message} vehicles={vehicles} /><Field label="Liters"><Input type="number" min="0.01" step="0.01" {...fuelForm.register("liters", { required: true, min: 0.01 })} /></Field><Field label="Total cost"><Input type="number" min="0.01" step="0.01" {...fuelForm.register("cost", { required: true, min: 0.01 })} /></Field><Field label="Date"><Input type="date" {...fuelForm.register("date")} /></Field><div className="md:col-span-4"><Button type="submit" disabled={addFuel.isPending}>{addFuel.isPending ? "Saving..." : "Save fuel log"}</Button></div></form></FormCard>}
    {mode === "expense" && <FormCard title="Add expense" onClose={() => setMode(null)}><form className="grid gap-4 md:grid-cols-3" onSubmit={expenseForm.handleSubmit((data) => addExpense.mutate({ ...data, amount: Number(data.amount), description: data.description || undefined }))}><VehicleField register={expenseForm.register} error={expenseForm.formState.errors.vehicleId?.message} vehicles={vehicles} /><Field label="Expense type"><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" {...expenseForm.register("type")}><option value="TOLL">Toll</option><option value="MAINTENANCE">Maintenance</option><option value="OTHER">Other</option></select></Field><Field label="Amount"><Input type="number" min="0.01" {...expenseForm.register("amount", { required: true, min: 0.01 })} /></Field><Field label="Date"><Input type="date" {...expenseForm.register("date")} /></Field><Field label="Description"><Input placeholder="Optional note" {...expenseForm.register("description")} /></Field><div className="flex items-end"><Button type="submit" disabled={addExpense.isPending}>{addExpense.isPending ? "Saving..." : "Save expense"}</Button></div></form></FormCard>}
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Fuel spend" value={`₹${fuelCost.toLocaleString()}`} icon={<Fuel className="h-5 w-5 text-blue-600" />} /><Metric label="Other expenses" value={`₹${expenseCost.toLocaleString()}`} icon={<ReceiptText className="h-5 w-5 text-violet-600" />} /><Metric label="Recorded entries" value={fuelLogs.length + expenses.length} icon={<ReceiptText className="h-5 w-5 text-emerald-600" />} /></div>
    <div className="grid gap-4 lg:grid-cols-2"><LogTable title="Fuel logs" loading={fuelLoading}><thead className="border-b text-muted-foreground"><tr><th className="p-3">Vehicle</th><th className="p-3">Date</th><th className="p-3">Liters</th><th className="p-3 text-right">Cost</th></tr></thead><tbody>{fuelLogs.map((log) => <tr className="border-b last:border-0" key={log.id}><td className="p-3"><p className="font-medium">{log.vehicle.name}</p><p className="text-xs text-muted-foreground">{log.vehicle.registrationNumber}</p></td><td className="p-3">{new Date(log.date).toLocaleDateString()}</td><td className="p-3">{log.liters} L</td><td className="p-3 text-right">₹{log.cost.toLocaleString()}</td></tr>)}</tbody></LogTable><LogTable title="Expense entries" loading={expenseLoading}><thead className="border-b text-muted-foreground"><tr><th className="p-3">Vehicle</th><th className="p-3">Type</th><th className="p-3">Date</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{expenses.map((expense) => <tr className="border-b last:border-0" key={expense.id}><td className="p-3"><p className="font-medium">{expense.vehicle.name}</p><p className="text-xs text-muted-foreground">{expense.description || expense.vehicle.registrationNumber}</p></td><td className="p-3">{expense.type}</td><td className="p-3">{new Date(expense.date).toLocaleDateString()}</td><td className="p-3 text-right">₹{expense.amount.toLocaleString()}</td></tr>)}</tbody></LogTable></div></div>;
}
function FormCard({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <Card><CardContent className="pt-6"><div className="mb-5 flex justify-between"><h3 className="font-semibold">{title}</h3><Button size="sm" variant="ghost" onClick={onClose}><X className="h-4 w-4" /></Button></div>{children}</CardContent></Card>; } function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; } function VehicleField({ register, error, vehicles }: { register: any; error?: string; vehicles: { id: string; name: string; registrationNumber: string }[] }) { return <Field label="Vehicle"><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" {...register("vehicleId", { required: "Select a vehicle" })}><option value="">Select vehicle</option>{vehicles.map((v) => <option key={v.id} value={v.id}>{v.name} · {v.registrationNumber}</option>)}</select>{error && <p className="text-xs text-destructive">{error}</p>}</Field>; } function Metric({ label, value, icon }: { label: string; value: string | number; icon: React.ReactNode }) { return <Card><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>{icon}</CardContent></Card>; } function LogTable({ title, loading, children }: { title: string; loading: boolean; children: React.ReactNode }) { return <Card><CardContent className="pt-6"><h3 className="mb-4 font-semibold">{title}</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm">{children}</table>{loading && <p className="p-4 text-center text-sm text-muted-foreground">Loading...</p>}</div></CardContent></Card>; }
