import { useState } from "react";
import { useForm } from "react-hook-form";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, MapPin, Package, Plus, Send, X, XCircle } from "lucide-react";
import toast from "react-hot-toast";
import { getAvailableDrivers } from "@/api/drivers";
import { cancelTrip, completeTrip, createTrip, dispatchTrip, getTrips, type CompleteTripPayload, type TripPayload } from "@/api/trips";
import { getAvailableVehicles } from "@/api/vehicles";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { TRIP_STATUS_LABELS, type Trip, type TripStatus } from "@/types";

const statuses: TripStatus[] = ["DRAFT", "DISPATCHED", "COMPLETED", "CANCELLED"];
const emptyTrip: TripPayload = { source: "", destination: "", cargoWeight: 0, plannedDistance: 0, vehicleId: "", driverId: "" };
function TripBadge({ status }: { status: TripStatus }) { const colors: Record<TripStatus, string> = { DRAFT: "bg-slate-100 text-slate-700", DISPATCHED: "bg-blue-100 text-blue-800", COMPLETED: "bg-emerald-100 text-emerald-800", CANCELLED: "bg-red-100 text-red-700" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${colors[status]}`}>{TRIP_STATUS_LABELS[status]}</span>; }

export function TripsPage() {
  const queryClient = useQueryClient(); const [showCreate, setShowCreate] = useState(false); const [statusFilter, setStatusFilter] = useState<"" | TripStatus>(""); const [completing, setCompleting] = useState<Trip | null>(null);
  const { data: trips = [], isLoading } = useQuery({ queryKey: ["trips", statusFilter], queryFn: () => getTrips(statusFilter ? { status: statusFilter } : undefined) }); const { data: vehicles = [] } = useQuery({ queryKey: ["available-vehicles"], queryFn: getAvailableVehicles, enabled: showCreate }); const { data: drivers = [] } = useQuery({ queryKey: ["available-drivers"], queryFn: getAvailableDrivers, enabled: showCreate });
  const tripForm = useForm<TripPayload>({ defaultValues: emptyTrip }); const completeForm = useForm<CompleteTripPayload>(); const refresh = () => { queryClient.invalidateQueries({ queryKey: ["trips"] }); queryClient.invalidateQueries({ queryKey: ["available-vehicles"] }); queryClient.invalidateQueries({ queryKey: ["available-drivers"] }); queryClient.invalidateQueries({ queryKey: ["dashboard-kpis"] }); };
  const create = useMutation({ mutationFn: createTrip, onSuccess: () => { toast.success("Trip saved as draft"); setShowCreate(false); tripForm.reset(emptyTrip); refresh(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to create trip") }); const dispatch = useMutation({ mutationFn: dispatchTrip, onSuccess: () => { toast.success("Trip dispatched; driver and vehicle are now on trip"); refresh(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to dispatch trip") }); const cancel = useMutation({ mutationFn: cancelTrip, onSuccess: () => { toast.success("Trip cancelled"); refresh(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to cancel trip") }); const complete = useMutation({ mutationFn: ({ id, data }: { id: string; data: CompleteTripPayload }) => completeTrip(id, data), onSuccess: () => { toast.success("Trip completed and resources released"); setCompleting(null); refresh(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to complete trip") });
  const selectedVehicle = vehicles.find((vehicle) => vehicle.id === tripForm.watch("vehicleId"));
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-primary">Dispatch control</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Trip management</h2><p className="mt-1 text-muted-foreground">Create, dispatch, complete, and cancel trips with protected status transitions.</p></div><Button onClick={() => setShowCreate(true)}><Plus className="h-4 w-4" /> Create trip</Button></div>
    {showCreate && <Card><CardContent className="pt-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">New dispatch plan</h3><p className="text-sm text-muted-foreground">Only available vehicles and compliant drivers can be selected.</p></div><Button size="sm" variant="ghost" onClick={() => setShowCreate(false)}><X className="h-4 w-4" /></Button></div><form className="grid gap-4 md:grid-cols-2 lg:grid-cols-3" onSubmit={tripForm.handleSubmit((data) => create.mutate({ ...data, cargoWeight: Number(data.cargoWeight), plannedDistance: Number(data.plannedDistance) }))}><Field label="Source" error={tripForm.formState.errors.source?.message}><Input placeholder="Mumbai" {...tripForm.register("source", { required: "Required" })} /></Field><Field label="Destination" error={tripForm.formState.errors.destination?.message}><Input placeholder="Pune" {...tripForm.register("destination", { required: "Required" })} /></Field><Field label="Cargo weight (kg)" error={tripForm.formState.errors.cargoWeight?.message}><Input type="number" min="1" {...tripForm.register("cargoWeight", { required: "Required", min: { value: 1, message: "Must be above 0" } })} /></Field><Field label="Planned distance (km)" error={tripForm.formState.errors.plannedDistance?.message}><Input type="number" min="1" {...tripForm.register("plannedDistance", { required: "Required", min: { value: 1, message: "Must be above 0" } })} /></Field><Field label="Available vehicle" error={tripForm.formState.errors.vehicleId?.message}><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" {...tripForm.register("vehicleId", { required: "Choose a vehicle" })}><option value="">Select vehicle</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.name} · {vehicle.registrationNumber} · {vehicle.maxLoadCapacity} kg</option>)}</select>{selectedVehicle && <p className="text-xs text-muted-foreground">Capacity: {selectedVehicle.maxLoadCapacity} kg</p>}</Field><Field label="Available driver" error={tripForm.formState.errors.driverId?.message}><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" {...tripForm.register("driverId", { required: "Choose a driver" })}><option value="">Select driver</option>{drivers.map((driver) => <option key={driver.id} value={driver.id}>{driver.name} · {driver.licenseCategory}</option>)}</select></Field><div className="flex items-end gap-3"><Button type="submit" disabled={create.isPending}>{create.isPending ? "Saving..." : "Save draft"}</Button><Button type="button" variant="outline" onClick={() => setShowCreate(false)}>Cancel</Button></div></form></CardContent></Card>}
    {completing && <Card className="border-emerald-200"><CardContent className="pt-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">Complete trip</h3><p className="text-sm text-muted-foreground">{completing.source} → {completing.destination}</p></div><Button variant="ghost" size="sm" onClick={() => setCompleting(null)}><X className="h-4 w-4" /></Button></div><form className="grid gap-4 md:grid-cols-3" onSubmit={completeForm.handleSubmit((data) => complete.mutate({ id: completing.id, data: { ...data, finalOdometer: Number(data.finalOdometer), fuelConsumed: Number(data.fuelConsumed), revenue: data.revenue ? Number(data.revenue) : undefined } }))}><Field label="Final odometer (km)"><Input type="number" min={completing.vehicle.odometer} {...completeForm.register("finalOdometer", { required: true })} /></Field><Field label="Fuel consumed (liters)"><Input type="number" min="0" step="0.01" {...completeForm.register("fuelConsumed", { required: true })} /></Field><Field label="Trip revenue (optional)"><Input type="number" min="0" {...completeForm.register("revenue")} /></Field><div className="md:col-span-3"><Button type="submit" disabled={complete.isPending}><CheckCircle2 className="h-4 w-4" /> {complete.isPending ? "Completing..." : "Complete trip"}</Button></div></form></CardContent></Card>}
    <Card><CardContent className="pt-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Trip board</h3><p className="mt-1 text-sm text-muted-foreground">Lifecycle: Draft → Dispatched → Completed / Cancelled</p></div><select className="h-9 rounded-lg border bg-background px-3 text-sm" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as "" | TripStatus)}><option value="">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{TRIP_STATUS_LABELS[status]}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="p-3">Route</th><th className="p-3">Vehicle & driver</th><th className="p-3">Cargo</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={5} className="p-6 text-center text-muted-foreground">Loading trips...</td></tr> : trips.length === 0 ? <tr><td colSpan={5} className="p-6 text-center text-muted-foreground">No trips created yet.</td></tr> : trips.map((trip) => <tr key={trip.id} className="border-b last:border-0"><td className="p-3"><p className="flex items-center gap-1 font-medium"><MapPin className="h-4 w-4 text-primary" />{trip.source} <span className="text-muted-foreground">→</span> {trip.destination}</p><p className="mt-1 text-xs text-muted-foreground">{trip.plannedDistance} km planned</p></td><td className="p-3"><p>{trip.vehicle.name} · {trip.vehicle.registrationNumber}</p><p className="text-xs text-muted-foreground">{trip.driver.name}</p></td><td className="p-3"><span className="inline-flex items-center gap-1"><Package className="h-4 w-4 text-muted-foreground" />{trip.cargoWeight} kg</span></td><td className="p-3"><TripBadge status={trip.status} /></td><td className="p-3"><div className="flex justify-end gap-2">{trip.status === "DRAFT" && <><Button size="sm" onClick={() => dispatch.mutate(trip.id)} disabled={dispatch.isPending}><Send className="h-3.5 w-3.5" /> Dispatch</Button><Button size="sm" variant="ghost" onClick={() => cancel.mutate(trip.id)}><XCircle className="h-4 w-4 text-destructive" /></Button></>}{trip.status === "DISPATCHED" && <><Button size="sm" variant="secondary" onClick={() => { setCompleting(trip); completeForm.reset({ finalOdometer: trip.vehicle.odometer, fuelConsumed: 0 }); }}><CheckCircle2 className="h-3.5 w-3.5" /> Complete</Button><Button size="sm" variant="ghost" onClick={() => cancel.mutate(trip.id)}><XCircle className="h-4 w-4 text-destructive" /></Button></>}</div></td></tr>)}</tbody></table></div></CardContent></Card></div>;
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}{error && <p className="text-xs text-destructive">{error}</p>}</div>; }
